[package]
name = "ellie_vm_gen2"
version = "0.1.0"
edition = "2021"

[dependencies]
ellie_core = { path = "../core", version = "0.7.3", default-features = false, features = ["std"] }
ellie_bytecode_gen2 = { path = "../bytecode_gen2", version = "0.1.0" }
byteorder = { version = "1.5.0", default-features = false }
num_enum = { version = "0.7.3", default-features = false }
