[package]
name = "ellie_vm"
version = "0.3.0"
edition = "2021"

[dependencies]
ellie_core = { path = "../core", version = "*", default-features = false }
mimalloc = { version="0.1.34", optional = true }

[features]
default = ["mimalloc"]
std = []